// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: agent_runtime/v1/agent_runtime.proto

package agentruntimepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntimeService_Run_FullMethodName            = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/Run"
	AgentRuntimeService_InterruptTurn_FullMethodName  = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/InterruptTurn"
	AgentRuntimeService_ResumeApproval_FullMethodName = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/ResumeApproval"
	AgentRuntimeService_GetRunState_FullMethodName    = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/GetRunState"
	AgentRuntimeService_ListRunStates_FullMethodName  = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/ListRunStates"
	AgentRuntimeService_ListEvents_FullMethodName     = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/ListEvents"
	AgentRuntimeService_Health_FullMethodName         = "/cyberstrike.agent_runtime.v1.AgentRuntimeService/Health"
)

// AgentRuntimeServiceClient is the client API for AgentRuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRuntimeServiceClient interface {
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RuntimeCommand, RuntimeEvent], error)
	InterruptTurn(ctx context.Context, in *InterruptTurnRequest, opts ...grpc.CallOption) (*InterruptTurnResponse, error)
	ResumeApproval(ctx context.Context, in *ResumeApprovalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error)
	GetRunState(ctx context.Context, in *GetRunStateRequest, opts ...grpc.CallOption) (*GetRunStateResponse, error)
	ListRunStates(ctx context.Context, in *ListRunStatesRequest, opts ...grpc.CallOption) (*ListRunStatesResponse, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type agentRuntimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeServiceClient(cc grpc.ClientConnInterface) AgentRuntimeServiceClient {
	return &agentRuntimeServiceClient{cc}
}

func (c *agentRuntimeServiceClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RuntimeCommand, RuntimeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntimeService_ServiceDesc.Streams[0], AgentRuntimeService_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RuntimeCommand, RuntimeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_RunClient = grpc.BidiStreamingClient[RuntimeCommand, RuntimeEvent]

func (c *agentRuntimeServiceClient) InterruptTurn(ctx context.Context, in *InterruptTurnRequest, opts ...grpc.CallOption) (*InterruptTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterruptTurnResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_InterruptTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) ResumeApproval(ctx context.Context, in *ResumeApprovalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntimeService_ServiceDesc.Streams[1], AgentRuntimeService_ResumeApproval_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ResumeApprovalRequest, RuntimeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_ResumeApprovalClient = grpc.ServerStreamingClient[RuntimeEvent]

func (c *agentRuntimeServiceClient) GetRunState(ctx context.Context, in *GetRunStateRequest, opts ...grpc.CallOption) (*GetRunStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunStateResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_GetRunState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) ListRunStates(ctx context.Context, in *ListRunStatesRequest, opts ...grpc.CallOption) (*ListRunStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunStatesResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_ListRunStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentRuntimeService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRuntimeServiceServer is the server API for AgentRuntimeService service.
// All implementations must embed UnimplementedAgentRuntimeServiceServer
// for forward compatibility.
type AgentRuntimeServiceServer interface {
	Run(grpc.BidiStreamingServer[RuntimeCommand, RuntimeEvent]) error
	InterruptTurn(context.Context, *InterruptTurnRequest) (*InterruptTurnResponse, error)
	ResumeApproval(*ResumeApprovalRequest, grpc.ServerStreamingServer[RuntimeEvent]) error
	GetRunState(context.Context, *GetRunStateRequest) (*GetRunStateResponse, error)
	ListRunStates(context.Context, *ListRunStatesRequest) (*ListRunStatesResponse, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

// UnimplementedAgentRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServiceServer struct{}

func (UnimplementedAgentRuntimeServiceServer) Run(grpc.BidiStreamingServer[RuntimeCommand, RuntimeEvent]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) InterruptTurn(context.Context, *InterruptTurnRequest) (*InterruptTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InterruptTurn not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) ResumeApproval(*ResumeApprovalRequest, grpc.ServerStreamingServer[RuntimeEvent]) error {
	return status.Error(codes.Unimplemented, "method ResumeApproval not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) GetRunState(context.Context, *GetRunStateRequest) (*GetRunStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunState not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) ListRunStates(context.Context, *ListRunStatesRequest) (*ListRunStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRunStates not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentRuntimeServiceServer) mustEmbedUnimplementedAgentRuntimeServiceServer() {}
func (UnimplementedAgentRuntimeServiceServer) testEmbeddedByValue()                             {}

// UnsafeAgentRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServiceServer will
// result in compilation errors.
type UnsafeAgentRuntimeServiceServer interface {
	mustEmbedUnimplementedAgentRuntimeServiceServer()
}

func RegisterAgentRuntimeServiceServer(s grpc.ServiceRegistrar, srv AgentRuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntimeService_ServiceDesc, srv)
}

func _AgentRuntimeService_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRuntimeServiceServer).Run(&grpc.GenericServerStream[RuntimeCommand, RuntimeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_RunServer = grpc.BidiStreamingServer[RuntimeCommand, RuntimeEvent]

func _AgentRuntimeService_InterruptTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).InterruptTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_InterruptTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).InterruptTurn(ctx, req.(*InterruptTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_ResumeApproval_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResumeApprovalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentRuntimeServiceServer).ResumeApproval(m, &grpc.GenericServerStream[ResumeApprovalRequest, RuntimeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntimeService_ResumeApprovalServer = grpc.ServerStreamingServer[RuntimeEvent]

func _AgentRuntimeService_GetRunState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).GetRunState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_GetRunState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).GetRunState(ctx, req.(*GetRunStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_ListRunStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).ListRunStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_ListRunStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).ListRunStates(ctx, req.(*ListRunStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntimeService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntimeService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRuntimeService_ServiceDesc is the grpc.ServiceDesc for AgentRuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyberstrike.agent_runtime.v1.AgentRuntimeService",
	HandlerType: (*AgentRuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InterruptTurn",
			Handler:    _AgentRuntimeService_InterruptTurn_Handler,
		},
		{
			MethodName: "GetRunState",
			Handler:    _AgentRuntimeService_GetRunState_Handler,
		},
		{
			MethodName: "ListRunStates",
			Handler:    _AgentRuntimeService_ListRunStates_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _AgentRuntimeService_ListEvents_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AgentRuntimeService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _AgentRuntimeService_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ResumeApproval",
			Handler:       _AgentRuntimeService_ResumeApproval_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent_runtime/v1/agent_runtime.proto",
}
