// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: agent_runtime/v1/agent_runtime.proto

package agentruntimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeCommand struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CommandId        string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ConversationId   string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RuntimeSessionId string                 `protobuf:"bytes,4,opt,name=runtime_session_id,json=runtimeSessionId,proto3" json:"runtime_session_id,omitempty"`
	Message          string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	ContextJson      string                 `protobuf:"bytes,6,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	Reason           string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	ContinueAfter    bool                   `protobuf:"varint,8,opt,name=continue_after,json=continueAfter,proto3" json:"continue_after,omitempty"`
	RequestId        string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Decision         string                 `protobuf:"bytes,10,opt,name=decision,proto3" json:"decision,omitempty"`
	ApprovalMessage  string                 `protobuf:"bytes,11,opt,name=approval_message,json=approvalMessage,proto3" json:"approval_message,omitempty"`
	RawJson          string                 `protobuf:"bytes,100,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RuntimeCommand) Reset() {
	*x = RuntimeCommand{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCommand) ProtoMessage() {}

func (x *RuntimeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCommand.ProtoReflect.Descriptor instead.
func (*RuntimeCommand) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeCommand) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RuntimeCommand) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RuntimeCommand) GetRuntimeSessionId() string {
	if x != nil {
		return x.RuntimeSessionId
	}
	return ""
}

func (x *RuntimeCommand) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeCommand) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *RuntimeCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RuntimeCommand) GetContinueAfter() bool {
	if x != nil {
		return x.ContinueAfter
	}
	return false
}

func (x *RuntimeCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RuntimeCommand) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *RuntimeCommand) GetApprovalMessage() string {
	if x != nil {
		return x.ApprovalMessage
	}
	return ""
}

func (x *RuntimeCommand) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type RuntimeEvent struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Type                    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CommandId               string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ConversationId          string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RuntimeSessionId        string                 `protobuf:"bytes,4,opt,name=runtime_session_id,json=runtimeSessionId,proto3" json:"runtime_session_id,omitempty"`
	TurnId                  string                 `protobuf:"bytes,5,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Delta                   string                 `protobuf:"bytes,6,opt,name=delta,proto3" json:"delta,omitempty"`
	Accumulated             string                 `protobuf:"bytes,7,opt,name=accumulated,proto3" json:"accumulated,omitempty"`
	Response                string                 `protobuf:"bytes,8,opt,name=response,proto3" json:"response,omitempty"`
	Reason                  string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	Message                 string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	Items                   []*PlanItem            `protobuf:"bytes,11,rep,name=items,proto3" json:"items,omitempty"`
	ToolCallId              string                 `protobuf:"bytes,12,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName                string                 `protobuf:"bytes,13,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson           string                 `protobuf:"bytes,14,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	Result                  string                 `protobuf:"bytes,15,opt,name=result,proto3" json:"result,omitempty"`
	Error                   string                 `protobuf:"bytes,16,opt,name=error,proto3" json:"error,omitempty"`
	RequestId               string                 `protobuf:"bytes,17,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Permission              string                 `protobuf:"bytes,18,opt,name=permission,proto3" json:"permission,omitempty"`
	Decision                string                 `protobuf:"bytes,19,opt,name=decision,proto3" json:"decision,omitempty"`
	Summary                 string                 `protobuf:"bytes,20,opt,name=summary,proto3" json:"summary,omitempty"`
	TaskId                  string                 `protobuf:"bytes,21,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Strategy                string                 `protobuf:"bytes,22,opt,name=strategy,proto3" json:"strategy,omitempty"`
	InputMessageCount       int64                  `protobuf:"varint,23,opt,name=input_message_count,json=inputMessageCount,proto3" json:"input_message_count,omitempty"`
	InputChars              int64                  `protobuf:"varint,24,opt,name=input_chars,json=inputChars,proto3" json:"input_chars,omitempty"`
	ReplacementMessageCount int64                  `protobuf:"varint,25,opt,name=replacement_message_count,json=replacementMessageCount,proto3" json:"replacement_message_count,omitempty"`
	ArtifactPath            string                 `protobuf:"bytes,26,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	EventId                 string                 `protobuf:"bytes,27,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	RuntimeEventType        string                 `protobuf:"bytes,28,opt,name=runtime_event_type,json=runtimeEventType,proto3" json:"runtime_event_type,omitempty"`
	RuntimeTraceJson        string                 `protobuf:"bytes,29,opt,name=runtime_trace_json,json=runtimeTraceJson,proto3" json:"runtime_trace_json,omitempty"`
	PayloadJson             string                 `protobuf:"bytes,30,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	OccurredAt              string                 `protobuf:"bytes,31,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Sequence                string                 `protobuf:"bytes,32,opt,name=sequence,proto3" json:"sequence,omitempty"`
	AssistantMessageId      string                 `protobuf:"bytes,33,opt,name=assistant_message_id,json=assistantMessageId,proto3" json:"assistant_message_id,omitempty"`
	RawJson                 string                 `protobuf:"bytes,100,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RuntimeEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RuntimeEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RuntimeEvent) GetRuntimeSessionId() string {
	if x != nil {
		return x.RuntimeSessionId
	}
	return ""
}

func (x *RuntimeEvent) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *RuntimeEvent) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *RuntimeEvent) GetAccumulated() string {
	if x != nil {
		return x.Accumulated
	}
	return ""
}

func (x *RuntimeEvent) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *RuntimeEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RuntimeEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RuntimeEvent) GetItems() []*PlanItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *RuntimeEvent) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *RuntimeEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *RuntimeEvent) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

func (x *RuntimeEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *RuntimeEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RuntimeEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RuntimeEvent) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *RuntimeEvent) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *RuntimeEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *RuntimeEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RuntimeEvent) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *RuntimeEvent) GetInputMessageCount() int64 {
	if x != nil {
		return x.InputMessageCount
	}
	return 0
}

func (x *RuntimeEvent) GetInputChars() int64 {
	if x != nil {
		return x.InputChars
	}
	return 0
}

func (x *RuntimeEvent) GetReplacementMessageCount() int64 {
	if x != nil {
		return x.ReplacementMessageCount
	}
	return 0
}

func (x *RuntimeEvent) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *RuntimeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RuntimeEvent) GetRuntimeEventType() string {
	if x != nil {
		return x.RuntimeEventType
	}
	return ""
}

func (x *RuntimeEvent) GetRuntimeTraceJson() string {
	if x != nil {
		return x.RuntimeTraceJson
	}
	return ""
}

func (x *RuntimeEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *RuntimeEvent) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

func (x *RuntimeEvent) GetSequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

func (x *RuntimeEvent) GetAssistantMessageId() string {
	if x != nil {
		return x.AssistantMessageId
	}
	return ""
}

func (x *RuntimeEvent) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type PlanItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Priority      string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanItem) Reset() {
	*x = PlanItem{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanItem) ProtoMessage() {}

func (x *PlanItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanItem.ProtoReflect.Descriptor instead.
func (*PlanItem) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *PlanItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanItem) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *PlanItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlanItem) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

type InterruptTurnRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ContinueAfter  bool                   `protobuf:"varint,3,opt,name=continue_after,json=continueAfter,proto3" json:"continue_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterruptTurnRequest) Reset() {
	*x = InterruptTurnRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptTurnRequest) ProtoMessage() {}

func (x *InterruptTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptTurnRequest.ProtoReflect.Descriptor instead.
func (*InterruptTurnRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *InterruptTurnRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *InterruptTurnRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InterruptTurnRequest) GetContinueAfter() bool {
	if x != nil {
		return x.ContinueAfter
	}
	return false
}

type InterruptTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptTurnResponse) Reset() {
	*x = InterruptTurnResponse{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptTurnResponse) ProtoMessage() {}

func (x *InterruptTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptTurnResponse.ProtoReflect.Descriptor instead.
func (*InterruptTurnResponse) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptTurnResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *InterruptTurnResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeApprovalRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommandId        string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ConversationId   string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RuntimeSessionId string                 `protobuf:"bytes,3,opt,name=runtime_session_id,json=runtimeSessionId,proto3" json:"runtime_session_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Decision         string                 `protobuf:"bytes,5,opt,name=decision,proto3" json:"decision,omitempty"`
	Message          string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ContextJson      string                 `protobuf:"bytes,7,opt,name=context_json,json=contextJson,proto3" json:"context_json,omitempty"`
	RawJson          string                 `protobuf:"bytes,100,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResumeApprovalRequest) Reset() {
	*x = ResumeApprovalRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeApprovalRequest) ProtoMessage() {}

func (x *ResumeApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeApprovalRequest.ProtoReflect.Descriptor instead.
func (*ResumeApprovalRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *ResumeApprovalRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ResumeApprovalRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ResumeApprovalRequest) GetRuntimeSessionId() string {
	if x != nil {
		return x.RuntimeSessionId
	}
	return ""
}

func (x *ResumeApprovalRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResumeApprovalRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResumeApprovalRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResumeApprovalRequest) GetContextJson() string {
	if x != nil {
		return x.ContextJson
	}
	return ""
}

func (x *ResumeApprovalRequest) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type GetRunStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRunStateRequest) Reset() {
	*x = GetRunStateRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStateRequest) ProtoMessage() {}

func (x *GetRunStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStateRequest.ProtoReflect.Descriptor instead.
func (*GetRunStateRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *GetRunStateRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type GetRunStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *RunState              `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRunStateResponse) Reset() {
	*x = GetRunStateResponse{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRunStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRunStateResponse) ProtoMessage() {}

func (x *GetRunStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRunStateResponse.ProtoReflect.Descriptor instead.
func (*GetRunStateResponse) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *GetRunStateResponse) GetState() *RunState {
	if x != nil {
		return x.State
	}
	return nil
}

type ListRunStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunStatesRequest) Reset() {
	*x = ListRunStatesRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunStatesRequest) ProtoMessage() {}

func (x *ListRunStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunStatesRequest.ProtoReflect.Descriptor instead.
func (*ListRunStatesRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{8}
}

type ListRunStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*RunState            `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunStatesResponse) Reset() {
	*x = ListRunStatesResponse{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunStatesResponse) ProtoMessage() {}

func (x *ListRunStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunStatesResponse.ProtoReflect.Descriptor instead.
func (*ListRunStatesResponse) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *ListRunStatesResponse) GetStates() []*RunState {
	if x != nil {
		return x.States
	}
	return nil
}

type ListEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AfterEventId   string                 `protobuf:"bytes,2,opt,name=after_event_id,json=afterEventId,proto3" json:"after_event_id,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventsRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListEventsRequest) GetAfterEventId() string {
	if x != nil {
		return x.AfterEventId
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RuntimeEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *ListEventsResponse) GetEvents() []*RuntimeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type RunState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConversationId     string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RuntimeSessionId   string                 `protobuf:"bytes,2,opt,name=runtime_session_id,json=runtimeSessionId,proto3" json:"runtime_session_id,omitempty"`
	TurnId             string                 `protobuf:"bytes,3,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	AssistantMessageId string                 `protobuf:"bytes,7,opt,name=assistant_message_id,json=assistantMessageId,proto3" json:"assistant_message_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunState) Reset() {
	*x = RunState{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunState) ProtoMessage() {}

func (x *RunState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunState.ProtoReflect.Descriptor instead.
func (*RunState) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *RunState) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *RunState) GetRuntimeSessionId() string {
	if x != nil {
		return x.RuntimeSessionId
	}
	return ""
}

func (x *RunState) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *RunState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RunState) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RunState) GetAssistantMessageId() string {
	if x != nil {
		return x.AssistantMessageId
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{13}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runtime_v1_agent_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_runtime_v1_agent_runtime_proto protoreflect.FileDescriptor

const file_agent_runtime_v1_agent_runtime_proto_rawDesc = "" +
	"\n" +
	"$agent_runtime/v1/agent_runtime.proto\x12\x1ccyberstrike.agent_runtime.v1\"\x97\x03\n" +
	"\x0eRuntimeCommand\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12,\n" +
	"\x12runtime_session_id\x18\x04 \x01(\tR\x10runtimeSessionId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12!\n" +
	"\fcontext_json\x18\x06 \x01(\tR\vcontextJson\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12%\n" +
	"\x0econtinue_after\x18\b \x01(\bR\rcontinueAfter\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x1a\n" +
	"\bdecision\x18\n" +
	" \x01(\tR\bdecision\x12)\n" +
	"\x10approval_message\x18\v \x01(\tR\x0fapprovalMessage\x12\x19\n" +
	"\braw_json\x18d \x01(\tR\arawJson\"\x89\t\n" +
	"\fRuntimeEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12,\n" +
	"\x12runtime_session_id\x18\x04 \x01(\tR\x10runtimeSessionId\x12\x17\n" +
	"\aturn_id\x18\x05 \x01(\tR\x06turnId\x12\x14\n" +
	"\x05delta\x18\x06 \x01(\tR\x05delta\x12 \n" +
	"\vaccumulated\x18\a \x01(\tR\vaccumulated\x12\x1a\n" +
	"\bresponse\x18\b \x01(\tR\bresponse\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\x12<\n" +
	"\x05items\x18\v \x03(\v2&.cyberstrike.agent_runtime.v1.PlanItemR\x05items\x12 \n" +
	"\ftool_call_id\x18\f \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\r \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x0e \x01(\tR\rargumentsJson\x12\x16\n" +
	"\x06result\x18\x0f \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x10 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"request_id\x18\x11 \x01(\tR\trequestId\x12\x1e\n" +
	"\n" +
	"permission\x18\x12 \x01(\tR\n" +
	"permission\x12\x1a\n" +
	"\bdecision\x18\x13 \x01(\tR\bdecision\x12\x18\n" +
	"\asummary\x18\x14 \x01(\tR\asummary\x12\x17\n" +
	"\atask_id\x18\x15 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bstrategy\x18\x16 \x01(\tR\bstrategy\x12.\n" +
	"\x13input_message_count\x18\x17 \x01(\x03R\x11inputMessageCount\x12\x1f\n" +
	"\vinput_chars\x18\x18 \x01(\x03R\n" +
	"inputChars\x12:\n" +
	"\x19replacement_message_count\x18\x19 \x01(\x03R\x17replacementMessageCount\x12#\n" +
	"\rartifact_path\x18\x1a \x01(\tR\fartifactPath\x12\x19\n" +
	"\bevent_id\x18\x1b \x01(\tR\aeventId\x12,\n" +
	"\x12runtime_event_type\x18\x1c \x01(\tR\x10runtimeEventType\x12,\n" +
	"\x12runtime_trace_json\x18\x1d \x01(\tR\x10runtimeTraceJson\x12!\n" +
	"\fpayload_json\x18\x1e \x01(\tR\vpayloadJson\x12\x1f\n" +
	"\voccurred_at\x18\x1f \x01(\tR\n" +
	"occurredAt\x12\x1a\n" +
	"\bsequence\x18  \x01(\tR\bsequence\x120\n" +
	"\x14assistant_message_id\x18! \x01(\tR\x12assistantMessageId\x12\x19\n" +
	"\braw_json\x18d \x01(\tR\arawJson\"b\n" +
	"\bPlanItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\"~\n" +
	"\x14InterruptTurnRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0econtinue_after\x18\x03 \x01(\bR\rcontinueAfter\"M\n" +
	"\x15InterruptTurnResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x02\n" +
	"\x15ResumeApprovalRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12,\n" +
	"\x12runtime_session_id\x18\x03 \x01(\tR\x10runtimeSessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1a\n" +
	"\bdecision\x18\x05 \x01(\tR\bdecision\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12!\n" +
	"\fcontext_json\x18\a \x01(\tR\vcontextJson\x12\x19\n" +
	"\braw_json\x18d \x01(\tR\arawJson\"=\n" +
	"\x12GetRunStateRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"S\n" +
	"\x13GetRunStateResponse\x12<\n" +
	"\x05state\x18\x01 \x01(\v2&.cyberstrike.agent_runtime.v1.RunStateR\x05state\"\x16\n" +
	"\x14ListRunStatesRequest\"W\n" +
	"\x15ListRunStatesResponse\x12>\n" +
	"\x06states\x18\x01 \x03(\v2&.cyberstrike.agent_runtime.v1.RunStateR\x06states\"x\n" +
	"\x11ListEventsRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12$\n" +
	"\x0eafter_event_id\x18\x02 \x01(\tR\fafterEventId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"X\n" +
	"\x12ListEventsResponse\x12B\n" +
	"\x06events\x18\x01 \x03(\v2*.cyberstrike.agent_runtime.v1.RuntimeEventR\x06events\"\xfd\x01\n" +
	"\bRunState\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12,\n" +
	"\x12runtime_session_id\x18\x02 \x01(\tR\x10runtimeSessionId\x12\x17\n" +
	"\aturn_id\x18\x03 \x01(\tR\x06turnId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x120\n" +
	"\x14assistant_message_id\x18\a \x01(\tR\x12assistantMessageId\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\x06\n" +
	"\x13AgentRuntimeService\x12c\n" +
	"\x03Run\x12,.cyberstrike.agent_runtime.v1.RuntimeCommand\x1a*.cyberstrike.agent_runtime.v1.RuntimeEvent(\x010\x01\x12x\n" +
	"\rInterruptTurn\x122.cyberstrike.agent_runtime.v1.InterruptTurnRequest\x1a3.cyberstrike.agent_runtime.v1.InterruptTurnResponse\x12s\n" +
	"\x0eResumeApproval\x123.cyberstrike.agent_runtime.v1.ResumeApprovalRequest\x1a*.cyberstrike.agent_runtime.v1.RuntimeEvent0\x01\x12r\n" +
	"\vGetRunState\x120.cyberstrike.agent_runtime.v1.GetRunStateRequest\x1a1.cyberstrike.agent_runtime.v1.GetRunStateResponse\x12x\n" +
	"\rListRunStates\x122.cyberstrike.agent_runtime.v1.ListRunStatesRequest\x1a3.cyberstrike.agent_runtime.v1.ListRunStatesResponse\x12o\n" +
	"\n" +
	"ListEvents\x12/.cyberstrike.agent_runtime.v1.ListEventsRequest\x1a0.cyberstrike.agent_runtime.v1.ListEventsResponse\x12c\n" +
	"\x06Health\x12+.cyberstrike.agent_runtime.v1.HealthRequest\x1a,.cyberstrike.agent_runtime.v1.HealthResponseB8Z6cyberstrike-ai/internal/agentruntime/pb;agentruntimepbb\x06proto3"

var (
	file_agent_runtime_v1_agent_runtime_proto_rawDescOnce sync.Once
	file_agent_runtime_v1_agent_runtime_proto_rawDescData []byte
)

func file_agent_runtime_v1_agent_runtime_proto_rawDescGZIP() []byte {
	file_agent_runtime_v1_agent_runtime_proto_rawDescOnce.Do(func() {
		file_agent_runtime_v1_agent_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_runtime_v1_agent_runtime_proto_rawDesc), len(file_agent_runtime_v1_agent_runtime_proto_rawDesc)))
	})
	return file_agent_runtime_v1_agent_runtime_proto_rawDescData
}

var file_agent_runtime_v1_agent_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agent_runtime_v1_agent_runtime_proto_goTypes = []any{
	(*RuntimeCommand)(nil),        // 0: cyberstrike.agent_runtime.v1.RuntimeCommand
	(*RuntimeEvent)(nil),          // 1: cyberstrike.agent_runtime.v1.RuntimeEvent
	(*PlanItem)(nil),              // 2: cyberstrike.agent_runtime.v1.PlanItem
	(*InterruptTurnRequest)(nil),  // 3: cyberstrike.agent_runtime.v1.InterruptTurnRequest
	(*InterruptTurnResponse)(nil), // 4: cyberstrike.agent_runtime.v1.InterruptTurnResponse
	(*ResumeApprovalRequest)(nil), // 5: cyberstrike.agent_runtime.v1.ResumeApprovalRequest
	(*GetRunStateRequest)(nil),    // 6: cyberstrike.agent_runtime.v1.GetRunStateRequest
	(*GetRunStateResponse)(nil),   // 7: cyberstrike.agent_runtime.v1.GetRunStateResponse
	(*ListRunStatesRequest)(nil),  // 8: cyberstrike.agent_runtime.v1.ListRunStatesRequest
	(*ListRunStatesResponse)(nil), // 9: cyberstrike.agent_runtime.v1.ListRunStatesResponse
	(*ListEventsRequest)(nil),     // 10: cyberstrike.agent_runtime.v1.ListEventsRequest
	(*ListEventsResponse)(nil),    // 11: cyberstrike.agent_runtime.v1.ListEventsResponse
	(*RunState)(nil),              // 12: cyberstrike.agent_runtime.v1.RunState
	(*HealthRequest)(nil),         // 13: cyberstrike.agent_runtime.v1.HealthRequest
	(*HealthResponse)(nil),        // 14: cyberstrike.agent_runtime.v1.HealthResponse
}
var file_agent_runtime_v1_agent_runtime_proto_depIdxs = []int32{
	2,  // 0: cyberstrike.agent_runtime.v1.RuntimeEvent.items:type_name -> cyberstrike.agent_runtime.v1.PlanItem
	12, // 1: cyberstrike.agent_runtime.v1.GetRunStateResponse.state:type_name -> cyberstrike.agent_runtime.v1.RunState
	12, // 2: cyberstrike.agent_runtime.v1.ListRunStatesResponse.states:type_name -> cyberstrike.agent_runtime.v1.RunState
	1,  // 3: cyberstrike.agent_runtime.v1.ListEventsResponse.events:type_name -> cyberstrike.agent_runtime.v1.RuntimeEvent
	0,  // 4: cyberstrike.agent_runtime.v1.AgentRuntimeService.Run:input_type -> cyberstrike.agent_runtime.v1.RuntimeCommand
	3,  // 5: cyberstrike.agent_runtime.v1.AgentRuntimeService.InterruptTurn:input_type -> cyberstrike.agent_runtime.v1.InterruptTurnRequest
	5,  // 6: cyberstrike.agent_runtime.v1.AgentRuntimeService.ResumeApproval:input_type -> cyberstrike.agent_runtime.v1.ResumeApprovalRequest
	6,  // 7: cyberstrike.agent_runtime.v1.AgentRuntimeService.GetRunState:input_type -> cyberstrike.agent_runtime.v1.GetRunStateRequest
	8,  // 8: cyberstrike.agent_runtime.v1.AgentRuntimeService.ListRunStates:input_type -> cyberstrike.agent_runtime.v1.ListRunStatesRequest
	10, // 9: cyberstrike.agent_runtime.v1.AgentRuntimeService.ListEvents:input_type -> cyberstrike.agent_runtime.v1.ListEventsRequest
	13, // 10: cyberstrike.agent_runtime.v1.AgentRuntimeService.Health:input_type -> cyberstrike.agent_runtime.v1.HealthRequest
	1,  // 11: cyberstrike.agent_runtime.v1.AgentRuntimeService.Run:output_type -> cyberstrike.agent_runtime.v1.RuntimeEvent
	4,  // 12: cyberstrike.agent_runtime.v1.AgentRuntimeService.InterruptTurn:output_type -> cyberstrike.agent_runtime.v1.InterruptTurnResponse
	1,  // 13: cyberstrike.agent_runtime.v1.AgentRuntimeService.ResumeApproval:output_type -> cyberstrike.agent_runtime.v1.RuntimeEvent
	7,  // 14: cyberstrike.agent_runtime.v1.AgentRuntimeService.GetRunState:output_type -> cyberstrike.agent_runtime.v1.GetRunStateResponse
	9,  // 15: cyberstrike.agent_runtime.v1.AgentRuntimeService.ListRunStates:output_type -> cyberstrike.agent_runtime.v1.ListRunStatesResponse
	11, // 16: cyberstrike.agent_runtime.v1.AgentRuntimeService.ListEvents:output_type -> cyberstrike.agent_runtime.v1.ListEventsResponse
	14, // 17: cyberstrike.agent_runtime.v1.AgentRuntimeService.Health:output_type -> cyberstrike.agent_runtime.v1.HealthResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_runtime_v1_agent_runtime_proto_init() }
func file_agent_runtime_v1_agent_runtime_proto_init() {
	if File_agent_runtime_v1_agent_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_runtime_v1_agent_runtime_proto_rawDesc), len(file_agent_runtime_v1_agent_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_runtime_v1_agent_runtime_proto_goTypes,
		DependencyIndexes: file_agent_runtime_v1_agent_runtime_proto_depIdxs,
		MessageInfos:      file_agent_runtime_v1_agent_runtime_proto_msgTypes,
	}.Build()
	File_agent_runtime_v1_agent_runtime_proto = out.File
	file_agent_runtime_v1_agent_runtime_proto_goTypes = nil
	file_agent_runtime_v1_agent_runtime_proto_depIdxs = nil
}
